apiVersion: aws.backstage.io/v1alpha
kind: AWSEnvironmentProvider
metadata:
  name: ${{values.name | dump}}
  prefix: ${{values.prefix | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  tags:
    - aws
    - aws-environment-provider
    - ecs
  env-type: ${{values.env_type}}
  aws-account: "${{values.aws_account}}"
  aws-region: ${{values.aws_region}}
  environment_role: "${{values.environment_role}}"
  vpc: ""
  cluster-name: ""
  operation-role: ""
  provisioning-role: ""
  audit-table: ""
  stack-name: ""
spec:
  type: environment-provider
  lifecycle: experimental
  owner: ${{values.owner | dump}}
